### ISSUE TITLE
Two mappings of the same file don't sync

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/libcx#13]
There is a test case in Samba, http://trac.netlabs.org/samba/browser/trunk/server/lib/replace/test/shared_mmap.c, where they assume that creating two MAP_SHARED mappings over the same file makes these memory regions automatically synced through that file. I.e. if you change bytes in one mapping and wait enough until the system synchronizes it with the file contents, reading the same relative bytes in the second mapping should return the same contents (and vise versa).

Strictly speaking, this is a violation of POSIX (first, POSIX doesn't guarantee when exactly memory contents is flushed back to the file except when it is unmapped, second, updating memory contents with new file data that was externally changed is also not a POSIX requirement). But given that it's present in Samba I guess many platforms support that. We can support it too given that both mappings are controlled by LIBCx, but I want to investigate more first (which platforms support that and how Samba uses mmap, exactly).

**Comment by dmik** [comment]
Just checked, this samba test succeeds on both Linux and OS X. Okay, it's almost a proof that we need it too. Still, want also to check Samba usage.

**Comment by dmik** [comment]
As far as I can judge from the Samba code, mmap there is used just like in the test case — they open the same file in several server processes, call mmap on it and expect that they get instant updates of memory in all processes if it gets changed in one.

The current scheme of allocating shared mmaps implies that each process allocates its own region even if there is another process already mapping the same file. This was done this way because it's simpler, allows two processes map small pieces of a (potentially huge) file and not have memory ranges allocated for the whole file, and, most important, having instant updates via the associated file isn't strictly required by POSIX. In theory, we can keep this scheme and use some mechanism to cause all other processes re-read the underlying file once it gets synced with the changes of one process but this looks like too much of a hassle and it will make such refreshing quite time and hard disk resource consuming.

So I now plan to change to the way how I initially planned to implement this: allocate a single shared memory region for each file and share it among all processes that mmap this file. This will cause the shared address space to be reserved for the entire file upfront (which will be a bit of a problem for huge files like hundreds of megs or more) but I think that situations when apps mmap only a small fraction of such files are quite rare (if any). The most common case is to mmap the entire file and this will cause address space pollution in either way.

**Comment by dmik** [comment]
The theoretical ability to create a mapping way beyond the real file that is supported in POSIX makes problems with the `DosAliasMem` approach. The thing is that once we create a root mapping for the whole file, we can't create an alias for it that's beyond the original memory range because `DosAliasMem` can't cross memory object boundaries by design.

I don't know how if this theoretical ability is really used though. We may simply don't care about that now (return EOVERFLOW in such a case). Note that the POSIX requirement to write beyond the EOF within the last page (see #18) will still be satisfied in this case.

Other than that, using aliases looks like a really good approach that will let us save memory in case if several processes map the same file in MAP_SHARED mode (or when the same process creates several MAP_PRIVATE mappings of the same file).

**Comment by dmik** [comment]
I more or less finished this task but faced another (small) issue. The code contains optimisation which gives the process the direct address of the shared file mapping if it's going to be the only user of it and access mode matches (r/w). However, then we get a difficulty when releasing such a mapping upon process termination as we don't know if `munmap` was already called for it or not. This is because we don't track PIDs which are given access to a particular shared mapping — instead we rely on the usage counter for a given memory region maintained by OS/2: if this counter for the given process reaches zero after DosFreeMem a subsequent DosQueryMem call will return PAG_FREE for the given address. However, since we "misuse" the region we allocate for the file mapping by directly passing it down to the application, we can't DosFreeMem it (as there may be other uses of this region within this process) and therefore we can't detect if we already released it in this process with `munmap` or not.

One way to solve this is to remove this optimisation that returns the file map address directly and use DosAliasMem on it even if there is only one user for this map but this will double address space pollution and I don't like it. The only other way for solving this is to track PIDs having access to the mapping but I don't like it either (too much hassle). I will think a bit more.

**Comment by dmik** [comment]
There is a way that seems to be more clear. Currently, we store shared mappings in one list in shared memory and private (e.g. process-specific) mappings — in another list. In fact, given that the new scheme allocates memory per file rather than per mapping and then shares this allocation between mappings (creating aliases when necessary), a logical step is to have a _single_ per-process list for both private and shared mappings. This way, we will know which shared mapping is used by which process w/o the need to associate PIDs with mappings. I also came up with that idea long ago but given that I didn't expect the mentioned POSIX violation I didn't want to implement it. Now it seems to be the time.

BTW, another benefit of this approach is that we will be able to sort the list of _all_ mappings (by address) to speed up lookups and also to implement releasing adjacent mappings with `munmap` (and even create holes in it) as required by POSIX in the future. We don't want to implement the latter now as it's really not very used. But I created a ticket #22 for it so we don't forget.

**Comment by dmik** [comment]
The above is done but I got one nasty stopper: it appears that `DosSetMem` always returns ERROR_ACCESS_DENIED when trying to remove PAG_WRITE from aliased memory (created with `DosAliasMem`) if this memory is created over a shared memory block that this process did not allocate (but received access to via `DosGetSharedMem`). This is really pity as it makes impossible to track writes to this region individually per process as I initially planned.

Note that removing PAG_WRITE _does_ work on aliased memory if the original region is allocated by the same process that creates an alias. Looks like inconsistency to me.

**Comment by dmik** [comment]
Hmm, I accidentally discovered a really crazy thing while testing.
1. `DosSetMem` actually works fine, it just returns a failure. I checked that with a subsequent `DosQueryMem`.
2. If the process that initially allocated shared memory also calls `DosAliasMem` on it, then `DosSetMem` in the receiving process stops returning ERROR_ACCESS_DENIED (and also works, of course).

This is kinda weird. But anyway, it works so we should just ignore the returned error value in this case.

**Comment by dmik** [comment]
One more thing needs to be done: we will have to link all memory mappings that use aliased memory into a list. This is needed to revoke PAG_WRITE from **all** aliases when the page is initially committed or flushed to make sure it is marked as dirty on the first write via **any** of the aliases. A failure to do so leads to cases when mapped memory is not properly flushed to the underlying file.

**Comment by dmik** [comment]
After almost finishing the above task I realised that this needs to be done for all aliases in ALL processes but we apparently can't change memory protection flags of another process... In order to make it work we will have to create some sort of synchronous IPC talk between all involved processes. This looks like too much work for this task. It appears to be cheaper to give up alias usage completely and just always use the shared memory directly.

The idea why I used aliases in the first place was to let each process have its own control over protection bits (see e.g. `mprotect`) and not interfere with other processes (as this is what I think POSIX has). But implementing it in userland turns out to be way too complex.

**Comment by dmik** [comment]
Just for the record, getting rid of aliases doesn't help a lot because OS/2 apparently maintains process-specific protection bits even for shared memory pages. This means that if `DosSetMem` revokes a PAG_WRITE permission from a shared page in one process, it is not revoked in all other processes that have access to this shared page.

In our case this means that if some process attempts to modify a clean page (that has PAG_WRITE removed), PAG_WRITE is set back and the page is made dirty. However, if some other process modifies this page too and happens to flush its contents before the first process does so, it will reset PAG_WRITE again and mark the page clean. However, PAG_WRITE is still there in the first process so any new write will not mark it as dirty and nobody will ever flush these changes (leading to loss of sync between the memory and the underlying file).

This happens because dirty bits are global in LIBCx while permission bits are per-process in OS/2. An obvious solution here is to use per-process dirty bit sets in LIBCx as well. I will see if there are any hidden traps. Maybe even the alias-based approach will work with that (which would be more desirable).

**Comment by dmik** [comment]
Using process-specific dirty maps helped to solve the issue. The SMB case works fully now, no problems so far. I'm now checking and aligning our mmap test suite to the new code to make sure I didn't break anything.

Given that memory protection attributes are per-process even for shared memory on OS/2 (I didn't know that and the docs of course don't mention it too), this implementation looks more than acceptable. I don't see any flaws in it so far (in terms of POSIX compliance) except #20 but this doesn't look a serious problem.

I will commit all the stuff in a while.

**Comment by psmedley** [comment]
Great work! Excited to test this!

Cheers,

Paul

**Comment by dmik** [comment]
The stuff is committed, all test cases work now. I will try the real life example (Samba tdbtorture) and will reopen this if I encounter any problems.

**Comment by dmik** [comment]
@psmedley Thanks Paul. Eager to see your test results! Though if you encounter any problems, please open new issues to avoid blowing this one. I will better do the same if tdbtorture fails.
