### ISSUE TITLE
Passing mmap region to pread causes it to return EINVAL

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/libcx#21]
If you create a shared, non-anonymous R/W mapping with `mmap` and then try to `pread` into it from a different file, `pread` will return EINVAL.

**Comment by dmik** [comment]
The real-life use case is RPM (its Berkley DB backend, where @ydario enabled mmap usage), here's the log: http://pastebin.com/3cpy88ch.

**Comment by dmik** [comment]
Okay, we are in big trouble here. `pread` uses `read` which eventually uses `DosRead`. And it seems that `DosRead` has some reentrancy problems so if it is interrupted by an exception handler it then returns some really strange values. In my case the value is `1244836` (`0x12FEA4`) which looks like garbage (some stack address). And this strange value is what causes `read` to return EINVAL (kLIBC returns EINVAL for all OS/2 APIRET codes it doesn't know).

I also see some evidence of this problem in kLIBC/EMX sources, e.g. `core_mem` in http://trac.netlabs.org/libc/browser/branches/libc-0.6/src/emx/src/os2/core.c. They overcome it by touching the first byte of each page with `touch` defined in http://trac.netlabs.org/libc/browser/branches/libc-0.6/src/emx/src/os2/emxdll.asm. However, the `_std_read` implementation in kLIBC uses raw `DosRead` without such touching.

The sad thing is that I don't see an easy way to solve this... The only one coming into my mind is to hack kLIBC and provide `SafeDosRead` there (where we also touch the first byte of every page to trigger the exception handler while not in `DosRead`) and use it instead of `DosRead` in all sensitive places in kLIBC itself as well as cause kLIBC based apps do the same by default (via `os2safe.h`, as already done for `DosOpen` and other folks that don't like high memory).

But Ideally we should fix the OS/2 kernel to make `DosRead` not faint in such cases. However, an opinion of @StevenLevine is welcome to understand if it's possible per se.

**Comment by dmik** [comment]
Forgot to mention that even if we go the `DosSafeRead` way, there may still be some 3rd party libraries not based on kLIBC that use `DosRead` directly and therefore will run into trouble doing so into a mapped region which hasn't been touched yet. So fixing the OS/2 kernel is the only error proof option here.

As a temporary solution at the LIBCx level, we may do touching from our `pread` override and also override the normal `read` to do the same there. But first I want to collect some opinions.

Also `DosWrite` needs to be checked for the presence of this defect.

**Comment by dmik** [comment]
The `DosWrite` call is free from this defect. I could safely write from an uncommitted mapped region to a file (this caused committing and reading from the underlying file while inside `DosWrite`). So only `DosRead` seems to be bogus.

**Comment by dmik** [comment]
The temporary solution is implemented by providing `read()`, `__read()`, `_stream_read()` and also `DosRead()` overrides that touch page bytes before passing the call down to the real function. Note that this isn't the ultimate solution (see above about third party libraries using `DosRead` directly) but fixing the OS/2 kernel is slightly beyond LIBCx (provided that we implemented the workaround) so it should be reported and tracked elsewhere.

**Comment by SilvanScherrer** [comment]
this issue was also reported to ArcaNoae. See https://mantis.arcanoae.com/view.php?id=573
