### ISSUE TITLE
Assertion failure when connecting to a Samba server when no current IP address

### ISSUE THREAD

**Issue by psmedley** [bitwiseworks/libcx#26]
Hi, whilst trying to root cause an ndpsmb.dll issue that may be a timing issue around the IP stack being initialised, I discovered that ndctl.exe from Netdrive was crashing under the following scenario.

dhcpstrt is removed from setup.cmd so that the system boots with no current IP address.
start ndctl.exe
Try and access the drives folder (thus having OS/2 enumerate all drives)
ndctl.exe closes

```
Error on the cmd session where ndctl run from has:
Assertion failed: pArray != (struct pollfd *) NULL, file U:/DEV/libcx0-git/src/poll/poll.c, line 301

Killed by SIGABRT
pid=0x0033 ppid=0x0000 tid=0x0002 slot=0x008f pri=0x0400 mc=0x0001 ps=0x0000
C:\NDFS\NDCTL.EXE
Process dumping was disabled, use DUMPPROC / PROCDUMP to enable it.
```

The logging libcx0.dll doesn't seem to have any relevant logging related to poll.

If I have a functioning IP stack, I don't get this failed assertion

**Comment by psmedley** [comment]
Commenting out the assertion fixes the issue, and samba logs appear normal for a missing server

**Comment by dmik** [comment]
This assertion means that `poll` has been passed a **wrong** value of NULL as the first argument. Do you know what code does that? libsmbclient?

Anyway, removing this assertion is not correct of course as it makes the NULL pointer accessible at some later stage (which just luckily is not triggered in your case). I checked Linux man (http://man7.org/linux/man-pages/man2/poll.2.html) and tried it on Mac, both indicate that `poll` should return EFAULT (Bad address) in such a case. I will do the same on OS/2.

**Comment by dmik** [comment]
Paul please check the new version and feel free to reopen/create a new issue if it still gives you any problems. And thanks for reporting.
