### ISSUE TITLE
Long runtime causes out of memory

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/libcx#30]
There is s suspicion that actively using a loaded LIBCx instance for quite some time (i.e. many mmap/pread/etc calls, like the Samba server does under heavy load during many days) eventually leads to some internal functions returning NULL after an unsuccessful memory allocation from the shared memory pool of LIBCx. Some such allocations assert, some just pass various kinds of failures to the application via errno. Reloading the LIBCx DLL (either by shutting down all using apps or rebooting) cures the disease.

**Comment by dmik** [comment]
Here is an assertion I once got from Samba:
```
[2016/12/15 13:53:46.203000,  0] lib/events.c:445(s3_event_debug)
  s3_event: poll() failed: 14:Bad address
Assertion failed: desc, file D:/Users/dmik/rpmbuild/BUILD/libcx-0.4/src/mmap/mmap.c, line 1258
[2016/12/15 14:49:39.000000,  0] smbd/server.c:582(smbd_accept_connection)
  smbd_accept_connection: sys_fork() failed: Interrupted system call
```

Line 1258 is a NULL assertion after `get_proc_desc(getpid());` in `mmap_init()`. I.e. it turns out that the new process started by Samba fails to allocate a process record and that is considered fatal in LIBCx.

**Comment by dmik** [comment]
Another problem which I believe has the same root is failing `git clone`:
```
D:>git clone https://github.com/psmedley/gcc
Cloning to 'gcc'...
error: unable to mmap 'D:/Coding/1/gcc/.git/config': Permission denied
fatal: ­Could not set 'core.filemode' to 'true'
```
I guess it's a pread/pwrite failure (as the current build of git doesn't use mmap, pread/pwrite are used instead).

**Comment by dmik** [comment]
I got Samba problems again, file listing works but files can't be opened, `smbclient.exe -U dmik //127.0.0.1/D -c 'get "test.png"'` gives this:
```
Domain=[LOCAL] OS=[OS/2] Server=[Samba 3.6.25-OS/2 v1.3.0-979]
parallel_read returned NT_STATUS_NO_MEMORY
```
And `libcx-stats.exe` shows this:
```
Reserved memory size:  2097152 bytes
Committed memory size: 2097152 bytes
Heap size total:       2096736 bytes
Heap size used now:    1585740 bytes
```
This is quite something! LIBCx went up to the maximum heap size (currently 2M). There is still some free memory though so this doesn't seem to be the case. But Samba seems to do A LOT of pread/pwrite or something like that and my guess that we run out of semaphores (each file in pread/pwrite uses a dedicated mutex). This needs to be checked.

**Comment by dmik** [comment]
Samba restart cures it of course and stats look like this afterwards:
```
Reserved memory size:  2097152 bytes
Committed memory size: 65536 bytes
Heap size total:       65120 bytes
Heap size used now:    2960 bytes
```
So it's definitely LIBCx resource usage trouble.

**Comment by AndiB-2** [comment]
I got the same error as dmik above -
```
Killed by SIGABRT
pid=0x40d8 ppid=0x3a9e tid=0x0001 slot=0x0178 pri=0x0400 mc=0x0001 ps=0x0010
P:\SAMBA\SMBD.EXE
Process dumping was disabled, use DUMPPROC / PROCDUMP to enable it.
[2017/03/11 11:09:29.902000,  0] smbd/server.c:570(smbd_accept_connection)
  smbd_accept_connection: sys_fork() failed: Connection timed out
Assertion failed: desc, file D:/Users/dmik/rpmbuild/BUILD/libcx-0.4.1/src/mmap/mmap.c, line 1258

```
I've killed and started smbd.exe and nmbd.exe numerous times but can't get samba to work again.

As I do not have any libcx-stats.exe here I tried to see what libcx packages are available but -

```
{0}[m:\] yum list libc*
Assertion failed: desc, file D:/Users/dmik/rpmbuild/BUILD/libcx-0.4.1/src/mmap/mmap.c, line 1258

Killed by SIGABRT
pid=0x4080 ppid=0x407f tid=0x0001 slot=0x017f pri=0x0200 mc=0x0001 ps=0x0010
P:\USR\BIN\PYTHON2.7.EXE
Process dumping was disabled, use DUMPPROC / PROCDUMP to enable it.


```
Maybe this gives additional hints to the root of the problem. System memory seems to be not the problem here -
`pm: 228352 sm: 131328  <---512---> pm: 834816 sm: 286320`

Btw. I can bring this system (samba) down quite fast - trying to copy 14GB in > 15.000 files from Win7 (TotalCommander) to my OS/2 share and the server (samba? libcx? ....) goes down. All in all I tried to copy about 25GB from Win7 over to OS/2 but it fails so often that I did some of them in chunks. Now more than 10GB are copied (after a lot of attempts within the last days) but some of the 15GB part still is open. If there is some newer version of any related component let me know and I'll test.

**Comment by dmik** [comment]
Intensive tests with enhanced logging and statistics accumulation have proven that the reason for the failure is running of the shared memory area in LIBCx (currently, 2MB) due too many `FileDesc` descriptors created at the same time and never deleted. Such a descriptors, in particular, is created for each file on which `pwrite` or `pread` is called (and this is what Samba does).

A simple test case is to run `git add -i` on a Mozilla repository over Samba (i.e. when OS/2 provides access to the repository's directory over the Samba server to another machine and that machine executes `git add -i`).  Here this leads to creation of 13800 `FileDesc` structs (yes, Mozilla has *A LOT* of files) and given that each struct also stores the file name (which is quite long in case of Mozilla due to subtrees etc, more than 100B each), this easily drains out all the 2MB of the shared heap. Note that besides draining out shared memory, this sometimes leads to draining out shared mutex semaphores because one is created for each file in order to implement LIBCx enhanced `pwrite` functionality.

A solution to this is to track LIBC `close` calls in order to free `FileDesc` and other resources when they are no more needed and #43 currently deals with that.

**Comment by dmik** [comment]
This isn't an issue any more after #43 (which significantly reduces memory usage in the Samba scenario — around 200 times less under heavy load involving dealing with about 13000 files) is done. There is still a crash (see https://github.com/bitwiseworks/libcx/issues/43#issuecomment-324998912) but since it has a different nature, I'm closing this one.
