### ISSUE TITLE
Exception c0000005 in Samba server

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/libcx#46]
With the latest version of LIBCx, I see a trap in NMBD.EXE with the following report:

[1832_01.TRP.txt](https://github.com/bitwiseworks/libcx/files/1299688/1832_01.TRP.txt)

and the following NMBD log:

[log.nmbd.txt](https://github.com/bitwiseworks/libcx/files/1299698/log.nmbd.txt)

Got it a couple of times and both happened when I was not using Samba (overnight). This doesn't relate to latest (1dc45ea1be62069cf49836189b74ac26fcb74fd0 and later) changes as the stock 0.6.0 release behaves the same.

From the stack trace, It's clear that a request to allocate a new block of memory reveals a LIBC heap corruption which eventually causes invalid memory access. This might be a regression of 0.6.0 compared to 0.5.3 but it's not very easy to find given that it's not easy to reproduce.

The new block of memory is needed by `get_file_desc_ex` for a new file on which `fcntl` advisory lock is called in F_SETLKW mode. So most likely, NMBD wants to lock some TDB file when it happens. The question is who corrupts the heap and when.

**Comment by DougB007** [comment]
I seem to have had this problem. I am using ArcaOS 5.0.1, with a few updates. I got a TRP file, that seems to be the same as posted above, followed 4 minutes later by two process dumps, then 8 libcx log files, another process dump, 8 more TRP files, 8 more process dump files, and even more when I tried to close the SAMBA server. When I tried to reboot, I got a TRAP 00e in AFINETK, after the file systems were closed out (so no dump, and my camera wasn't handy). This is the first TRP log.

[9B53_01.TRP.txt](https://github.com/bitwiseworks/libcx/files/1587900/9B53_01.TRP.txt)


For the record, I did NOT use SAMBA after the machine was booted. It was loaded, and ready, but not used.

Let me know if anything else might help to get this fixed. Thanks

**Comment by dmik** [comment]
I'm not seeing `get_file_desc_ex` crashes since long with the recent version (0.6.8), but I'm seeing another assertion from time to time which might be related:
```
Opened log at 2020-07-26 00:43:16.14
Process ID: 0x171c (5916) Parent PID: 0x4c (76) Type: 4
Exe hmte  : 0xd58 (C:\PROGRAMS\SAMBA\SMBD.EXE)
First arg : smbd
Second arg: 
Cur dir   : C:\PROGRAMS\SAMBA
CRT Module: LIBCN0 hmod=0xb05 (C:\USR\LIB\LIBCN0.DLL)
__libc_logInit: addr 0x1df3f259 iObj=0 offObj=0x4f259
   Millsecond Timestamp.
   |     Thread ID.
   |     |  Call Nesting Level.
   |     |  |   Log Group.
   |     |  |   |    Message Type.
   |     |  |   |    |    errno in hex (0xface if not available).
   |     |  |   |    |    |      Function Name.
   |     |  |   |    |    |      |       Millisconds In function (Optional).
   v     v  v   v    v    v      v       v
xxxxxxxx tt nn gggg dddd eeee function [(ms)]: message
LIBCx version : 0.6.8_dev
LIBCx module  : C:\USR\LOCAL\LIB\LIBCX0.DLL (hmod=0b0f)
007f6b99 01 ff 0000 Asrt: Assertion Failed!!!
007f6b99 01 ff 0000 Asrt: Function: <NULL>
007f6b99 01 ff 0000 Asrt: File:     D:/Coding/libcx/master/src/fcntl/fcntl.c
007f6b99 01 ff 0000 Asrt: Line:     152
007f6b99 01 ff 0000 Asrt: Expr:     l->pids && l->pids->used
007f6b99 01 ff 0000 Asrt: 
===== LIBCx resource usage =====
Reserved memory size:  2097152 bytes
Committed memory size: 196608 bytes
Heap size total:       196192 bytes
Heap size used now:    74036 bytes
ProcDesc structs used now:       87
FileDesc structs used now:       740
SharedFileDesc structs used now: 20
===== LIBCx global mutex owner =====
mutex handle: 800100af
owner PID:    171c (5916)
owner TID:    1
===== LIBCx stats end =====
```

And while working on #83, I suddenly found what caused the above assertion. It's the fact that `realloc` does not zero new memory but the code relies on that. It could lead to arbitrary PID values (and could have some other negative impact besides this assertion as well). Also, the code calling `realloc` didn't account for cases when the new memory block was moved. Once it were the case, the code would end up using the freed memory block! Side effects are even more dramatic and the above crash might be easily one of them.

I will commit the fix now. There was one more place using realloc and expecting zeroes in new memory. Will fix that too.

**Comment by dmik** [comment]
The above commit I believe fixes the above assertion. And given that no other crashes are seen since long, I'm closing this. To be reopened if/when it happens again.
