### ISSUE TITLE
libcx v0.6.2 on Samba 3 server aborts when client attempts to log in

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/libcx#53]
Backleveling to earlier build (2017-06-02, 24,923 bytes) alleviates this problem.

Minimal trap info:

[2018/06/18 11:15:43.690000,  0] smbd/server.c:1142(main)
  standard input is not a socket, assuming -D option
Assertion info: 6
Assertion failed: arc == NO_ERROR, file D:/Users/dmik/rpmbuild/BUILD/libcx-0.6.2/src/shared.c, line 557

Killed by SIGABRT
pid=0x003b ppid=0x0038 tid=0x0001 slot=0x0073 pri=0x0400 mc=0x0001 ps=0x0010
J:\SMB\SAMBA\SMBD.EXE
Process dumping was disabled, use DUMPPROC / PROCDUMP to enable it.

**Comment by dryeo** [comment]
@Lewis, have you tried
SET LIBCX HIGHMEM=2
in your environment?

**Comment by LewisR** [comment]
This is for an AN consulting client. The environment is eCS 2.1. We haven't tested the ramifications of that env setting here. Perhaps we should.

The short answer is no, we have not, Dave. Thanks for suggesting it.

**Comment by herwigb** [comment]
Which Samba revision?
You might try this one ftp://ftp.netlabs.org/pub/samba/server/samba-1-3-0-1022.wpi or even this one ftp://ftp.netlabs.org/pub/samba/server/test/samba-1-3-0-1044.wpi Basically this is a recompile to work with newer libcx.

**Comment by LewisR** [comment]
Looks like we used 1.3.0.1013, which is I think what we ship with ArcaOS 5.0.2.

Will test 1.3.0.1044 and report what happens.

**Comment by SilvanScherrer** [comment]
did you test already? It's a bit important, as a new libcx release is near

**Comment by Greggk** [comment]
Hi

Sorry for the late response. I have been traveling. Libcx 0.6.3 works fine here. Thanks

Gregg

**Comment by SilvanScherrer** [comment]
As Gregg said all is ok i closed the issue.
