### ISSUE TITLE
DosEnumAttribute should be wrapped and added to os2safe.h 

### ISSUE THREAD

**Issue by Greggk** [bitwiseworks/libcx#57]
It isn't high memory safe. I have more detail of the call sequence in doscall1.dll if needed.

**Comment by dmik** [comment]
No reason not to believe you :) Will be done at some point.

**Comment by dmik** [comment]
This is a wrong place though. I don't do any SafeXXX stuff in LIBCx. Please create a ticket here: https://github.com/bitwiseworks/libc.
