### ISSUE TITLE
Missing _SafeDosDevIOCtl in libcx although defined in os2safe.h

### ISSUE THREAD

**Issue by AndiB-2** [bitwiseworks/libcx#61]
I linked with -lcx and get 
`<<code>{0}[e:\_work\savedosdevioctl_test] make
  OBJS  main.o
  LIBS
  EXTRALIBS
gcc -lcx -Zexe -Zomf -Zmap -o SaveDosDevIOCtl_test main.o
weakld: error: Unresolved symbol (UNDEF) '_SafeDosDevIOCtl'.
weakld: info: The symbol is referenced by:
    T:\Temp\ldconv_main_o_17d5be09428140b28.obj
Ignoring unresolved externals reported from weak prelinker.
Error! E2028: _SafeDosDevIOCtl is an undefined reference
file T:/Temp\ldconv_main_o_17d5be09428140b28.obj(main.c): undefined symbol _SafeDosDevIOCtl
make.exe: *** [SaveDosDevIOCtl_test] Error 1
<code/>`>
My simple testcase includes a call to DosOpen too and this works as expected. But not DosDevIOCtl.

file:///E:/_work/SaveDosDevIOCtl_test/main.c
file:///E:/_work/SaveDosDevIOCtl_test/Makefile

Btw. our browsers are not supported anymore by github. Not sure if formating works as expected. Sorry if not. And there's not preview.

**Comment by AndiB-2** [comment]
Issue edit does not work and file attaching does not work too :-(

Here is main.c 

#include <os2safe.h>		

#include <os2.h>
#include <malloc.h>
#include <stdio.h>

#define     GENMAC_CATEGORY         0x99
#define     GENMAC_WRAPPER_OID_SET  0x41

typedef struct _PACKET_OID_DATA
	{

	ULONG       Oid ;
	int         Length ;
	char        Data[16] ;

	}PACKET_OID_DATA;

int main()
	{
	ULONG ParmInOut,DataInOut,rc ;
	ULONG Paras[10] ;
	static HFILE hf;
	ULONG ul;
  void *Handle;
	
	PACKET_OID_DATA *p;

	p = malloc(sizeof(PACKET_OID_DATA));
	
	Paras[0]  = 0 ;
	ParmInOut = 10*4 ;

	DataInOut = p->Length ;
	Paras[0]  = p->Oid ;
	Paras[1]  = p->Length ;

	printf("Start %s %s \n", __DATE__, __TIME__);

	rc = DosDevIOCtl( (int)Handle,GENMAC_CATEGORY,GENMAC_WRAPPER_OID_SET,
										&Paras[0]  ,ParmInOut,&ParmInOut,
										&p->Data[0],DataInOut,&DataInOut);



	rc |= DosOpen( (PCSZ) "dosopen.tst", &hf, &ul, 0, 0,
					OPEN_ACTION_CREATE_IF_NEW | OPEN_ACTION_REPLACE_IF_EXISTS,
					OPEN_SHARE_DENYNONE | OPEN_ACCESS_WRITEONLY, NULL);

	rc |= DosClose(hf);
	
	return rc;
	}


And makefile -
ifndef CC
CC=gcc
endif

CFLAGS = -MMD -Wall -g -O0
LDFLAGS=-lcx -Zexe -Zomf -Zmap

BINALL=SaveDosDevIOCtl_test

ALL = $(BINALL)

OBJS = main.o
OBJS +=

ifndef LDO
LDO=$(CC)
endif

Q=@
E=echo
ifeq ($(V), 1)
Q=
E=true
endif
ifeq ($(QUIET), 1)
Q=@
E=true
endif

SaveDosDevIOCtl_test: $(BCHECK) $(OBJS) $(EXTRA_progs)
	@$(E) "  OBJS " $(OBJS)
	@$(E) "  LIBS " $(LIBS)
	@$(E) "  EXTRALIBS " $(EXTRALIBS)
	$(LDO) $(LDFLAGS) -o SaveDosDevIOCtl_test $(OBJS) $(LIBS) $(EXTRALIBS)
	@$(E) "  LD " $@

SaveDosDevIOCtl_test.exe: SaveDosDevIOCtl_test
	mv -f $< $@

clean:
	rm -f *~ *.o *.d *.gcno *.gcda *.gcov *.exe *.map

**Comment by AndiB-2** [comment]
And again the compiler linker output in hope it's more readable now -

{0}[e:\_work\savedosdevioctl_test] make
  OBJS  main.o
  LIBS
  EXTRALIBS
gcc -lcx -Zexe -Zomf -Zmap -o SaveDosDevIOCtl_test main.o
weakld: error: Unresolved symbol (UNDEF) '_SafeDosDevIOCtl'.
weakld: info: The symbol is referenced by:
    T:\Temp\ldconv_main_o_17d5be09428140b28.obj
Ignoring unresolved externals reported from weak prelinker.
Error! E2028: _SafeDosDevIOCtl is an undefined reference
file T:/Temp\ldconv_main_o_17d5be09428140b28.obj(main.c): undefined symbol _SafeDosDevIOCtl
make.exe: *** [SaveDosDevIOCtl_test] Error 1

**Comment by dryeo** [comment]
On 11/05/18 11:15 AM, AndiB-2 wrote:
> Btw. our browsers are not supported anymore by github. Not sure if
> formating works as expected. Sorry if not. And there's not preview.

It works a lot better if you change the user agent to 52ESR, at least 
the 45ESR based ones. Haven't experimented too much though.

**Comment by AndiB-2** [comment]
Adding 
#define INCL_DOSDEVICES
#define INCL_DOEDEVIOCTL
cures this problem

What confused me was the error about DosDevIOCtl but no error for DosOpen. I got it now.
