### ISSUE TITLE
Add getrusage()

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libcx#69]
This API is more And more used/needed by ports.

See https://github.com/bitwiseworks/openjpeg-os2/commit/99b78fa922ca5781fd64392b50f3ccf62444da72 for a Implementation.

**Comment by dmik** [comment]
This actually should belong to LIBC as it's `sys/resources.h` already provides a prototype. So I will do it there.

**Comment by dmik** [comment]
Closing in favor of the above.
