### ISSUE TITLE
select() override is buggy in one case

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libcx#79]
given
rc = select(-1, NULL, NULL, NULL, &tv);
rc is 0 and ERRNO is 0 as well, while rc sould be -1 and ERRNO == EINVAL

the problem is line 144 in select.c, where max_fd + 1 is used. So libc select() gets fd 0 and then just does a wait.
I would check if fd is -1 very eraly and return with the right values.

**Comment by dmik** [comment]
Yes, there is a bug in LIBCx `select` which will send `nfds` = 0 to LIBCn `select` for any negative input `nfds` value (including -1). And I will fix that here. But that's actually not enough. LIBCn `select` is also bogus as it returns 0 on -1 as well. Will create a separate ticket for that.

**Comment by dmik** [comment]
Note that the fix in both LIBCx and LIBCn is identical — we can't rely on LIBCn here because we use nfds on our own.
