### ISSUE TITLE
touch_pages may go beyond the requested length

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/libcx#95]
We use `touch_pages` to fix edge cases in `DosRead` when implementing memory mapped files in LIBCx (see #21 for details) while implementing `pread` and similar calls.

However, it turned out that `touch_pages` may go beyond the requested length in some cases. See https://mantis.arcanoae.com/view.php?id=573 and specifically this:

>Re Paul's TRP. Yes, according to your analysis (which I can confirm) the inner loop may go beyond the len argument. My logic back in the day was to touch the whole region regardless of the requested length assuming it is going to be used anyway. But now I see that it's not actually what should be done there. First, it makes no sense to commit memory which isn't about to be touched by DosRead (and which may never be actually used). Second, it's possible that some region of initially "mapped" (allocated) memory was later "unmampped" by the application. From the OS/2 kernel POV, this region still belongs to the whole allocation (hence a large dos_len value from DosQueryMem). However, from the LIBCx mmap point of view, this region is no longer in operation so the mmap exception handler will not process it and will return XCPT_CONTINUE_SEARCH letting the exception be passed down to other exception handlers and eventually cause an application trap. LIBCx logs would tell us if it's really the case.

Attaching Paul's .TRP for reference: [AAD4_01.TRP.txt](https://github.com/bitwiseworks/libcx/files/6930974/AAD4_01.TRP.txt)

I will try to fix the inner loop in `touch_pages` so that it doesn't go beyond the requested loop.

And in the meanwhile I'm still requesting someone (@psmedley or @stevenlevine) to provide me LIBCx debug logs to prove that my quoted assumption is right and the fix is about to cover all such cases.

**Comment by dmik** [comment]
I uploaded the fixed DLL to http://rpm.netlabs.org/test/libcx0.7z. But please provide me with logs of the previous version anyway — to make sure the fix does exactly what we think.

**Comment by psmedley** [comment]
@dmik thanks for looking in to this issue. My OS/2 VM has been out of action for the past week, I expect to have it back up and running in the next 24 hours or so, and can then produce the requested logs and test that new DLL.

**Comment by psmedley** [comment]
Hi dmik, for some reason I couldn't get the libcx logs to work, despite setting LIBCX_TRACE.

However, I can confirm the trap is gone with the updated libcx0.dll - thanks!

**Comment by dmik** [comment]
@psmedley you need a debug build of LIBCx for that which you should build yourself with `kmk BUILD_TYPE=debug`. And then install this LIBCx as a system DLL and reboot (don't forget to set `LIBCX_TRACE=-all` to CONFIG.SYS to avoid huge spamming). And then set `LIBCX_TRACE=+all` in the needed session. Oh, and logs are now created in `/var/log/libcx`.

You can also omit putting the debug DLL to the system location and use the usual BEGINLIBPATH/LIBPATSTRICT=T thingy but this might not work depending on how other DLLs are used by your app.

**Comment by psmedley** [comment]
Logs at https://smedley.id.au/tmp/httpd-log.zip

**Comment by dmik** [comment]
Yes, the logs confirm that it was a partial `unmap` from some code which broke the whole region into pieces with the hole in the middle (from the mmap POV). And a subsequent `touch_pages` call would trigger a write to this hole which mmap would not recognize as its own and let the exception go (with a subsequent crash).

I will commit the fix.
